### ISSUE TITLE
Agree on skip logic and fix it

### ISSUE THREAD

**Issue by veruu** [RH-FMK/sktm#54]
Right now for PW2, we are skipping the patch series if they contain one of SKIP patterns in their name, however we are not checking the names of patches themselves. This doesn't seem like a correct strategy since a single patchset can span both kernel and appropriate tools, see [for example these netdev series](https://patchwork.ozlabs.org/project/netdev/list/?series=41490&state=%2A&archive=both). By checking only series' names, this won't be detected and we'd get a patch application error as we try to apply the patches meant for tools.

For PW1 interface, skipping is based on names of patches, not series (since there are no series, hah), which seems like the correct behavior - we should be fine by skipping tools patches from the patchset since they *shouldn't* be touching kernel code.

I'd say we should implement the same granularity for PW2 as well - check the series name as we do, but also check names of the individual patches so we can skip them properly.

I'll do this as a part of patchwork rework if there isn't anything I'm missing that would prevent it. @spbnick please shout if you see a hole in the above.

**Comment by spbnick** [comment]
I would have to rely on you to know the details of the skipping logic. Otherwise it absolutely makes sense to do the same thing both in PW1 and PW2. One thing about these skip patterns: I would like to see them in the configuration, not hard-coded, but it can wait.

In general, I think it might be easier for everyone involved to do the Patchwork interface cleanup in smaller steps rather than trying to do one big PR with everything in it :)

**Comment by veruu** [comment]
I already have a patch that allows extending skip patterns from command line in that pull. Anyways, I'll include the fix for this and then work on getting the pull merged because it's already pretty large, as you say.
